## NumPy 실습문제

1. 0으로 채워진 크기가 20인 배열을 생성하세요. 

In [3]:
import numpy as np
a = np.zeros(20)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

2. 0부터 15까지의 값을 갖는 4 x 4 행렬을 생성하세요. 

In [6]:
print(np.array(range(16)).reshape(4,4))
a = np.arange(16).reshape(4,4)
a

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

3. 길이가 10인데 세번째 요소만 1이고, 나머지 요소는 0인 배열을 생성하세요.

In [8]:
a = np.zeros(10)
a[3] = 1
a

array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0.])

4. 1에서 10까지의 값을 갖는 배열을 생성하세요.

In [14]:
a = np.arange(1,11)

5. 위의 배열의 순서를 거꾸로 바꿔주세요. 

In [18]:
a[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [44]:
a = [0, 10, 20, 30, 40, 50, 60, 70, 80, 90]
a[2:8:3]    # 인덱스 2부터 3씩 증가시키면서 인덱스 7까지 가져옴


[20, 50]

6. 4x4 단위행렬을 만드세요. (단위 행렬(영어: identity matrix)은 주대각선의 원소가 모두 1이며 나머지 원소는 모두 0인 정사각 행렬이다.)

In [19]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

7. 랜덤한 값을 가지는 3X3X3 배열을 생성하세요. 

In [22]:
arr = np.random.randn(3,3,3)
arr

array([[[-1.1275289 , -1.60148331,  0.08532539],
        [ 0.72181783,  0.09362782,  1.33067166],
        [-1.05518924,  0.94790985, -0.98185953]],

       [[ 0.79589358,  0.52444711,  0.04273791],
        [ 0.24962242,  0.85724619, -1.46556781],
        [ 0.60268586, -0.71405257, -0.41205491]],

       [[-0.34209964,  2.38641259, -0.99543415],
        [ 0.36522769,  1.62578638,  0.50465802],
        [ 1.45147373,  0.56592719, -0.01445223]]])

8. 위에서 생성한 배열 원소의 최대값, 최솟값을 구하세요. 

In [23]:
print(arr.max(),arr.min())

2.386412585532054 -1.6014833146547622


9. 20개의 랜덤한 값을 가진 배열을 생성하고, 그 배열의 평균값을 구하시오.  
    참고: numpy에서 평균을 구하는 함수 - mean() 

In [25]:
np.random.randn(20).mean()

0.36981078307264903

10. 4x4 의 2차원 배열을 생성하세요. 단 테두리는 1을 내부는 0으로 채워주세요. 

In [31]:
arr = np.ones((4,4))
arr[1:-1,1:-1] = 0
arr

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])