In [2]:
import numpy as np

In [3]:
#인덱싱  - 파이썬의 리스트와 동일한 개념으로 사용한다. 
# 1차원 벡터 인덱싱!!!   
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr1[3]

3

In [5]:
arr1[3] = 100
arr1

array([  0,   1,   2, 100,   4,   5,   6,   7,   8,   9])

In [7]:
#2차원 행렬의 인텍싱 
arr2 = np.arange(10).reshape(2,5)
arr2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [9]:
#인덱스를 ,로 구분해서 접근한다. 

arr2[1,2]

7

In [11]:
arr3 = np.arange(15).reshape(3,5)
arr3

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [12]:
arr3[1,-1]

9

In [13]:
arr3[1]

array([5, 6, 7, 8, 9])

In [15]:
arr4 = np.arange(30).reshape(3,5,2)
arr4

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]]])

In [16]:
arr4[0]

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [17]:
arr5 = np.arange(10,100,10).reshape(3,3)
arr5

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [18]:
arr5[0,2]

30

In [20]:
arr5[2,2]=95
arr5

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 95]])

In [21]:
arr5[1]

array([40, 50, 60])

In [22]:
arr5[0]=np.array([15,25,35])
arr5

array([[15, 25, 35],
       [40, 50, 60],
       [70, 80, 95]])

In [23]:
arr6 = np.array([1,2,3,4,5,6])
arr6[arr6>3]

array([4, 5, 6])

In [24]:
arr6[(arr6 % 2 ==0) ]

array([2, 4, 6])

In [25]:
#슬라이싱..  

arr7 = np.arange(10)
arr7

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
arr7[1:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
arr7[2:-3]

array([2, 3, 4, 5, 6])

In [28]:
#2차원 배열 슬라이싱
arr8 = np.arange(10).reshape(2,5)
arr8

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [32]:
arr8[:,:2]

array([[0, 1],
       [5, 6]])

In [33]:
arr9 = np.arange(36).reshape(6,6)
arr9

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [36]:
arr9[2,3:-1]

array([15, 16])

In [38]:
arr10 = np.arange(54).reshape(2,9,3)
arr10

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]],

       [[27, 28, 29],
        [30, 31, 32],
        [33, 34, 35],
        [36, 37, 38],
        [39, 40, 41],
        [42, 43, 44],
        [45, 46, 47],
        [48, 49, 50],
        [51, 52, 53]]])

In [39]:
arr10[:1, :2, :]

array([[[0, 1, 2],
        [3, 4, 5]]])

In [40]:
arr10[0,:2, :]

array([[0, 1, 2],
       [3, 4, 5]])

In [41]:
arr10[:2,:2,:]

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[27, 28, 29],
        [30, 31, 32]]])

In [42]:
arr11 = np.arange(15).reshape(3,5)
arr11

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [44]:
#ndarray의 shape 변경 방법...  
#ravel   -   파라미터 order --   'C' (row우선) 'F' - (colum 우선)

np.ravel(arr11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [48]:
np.ravel(arr11,order='F')

array([ 0,  5, 10,  1,  6, 11,  2,  7, 12,  3,  8, 13,  4,  9, 14])

In [49]:
np.ravel(arr10)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53])

In [50]:
np.ravel(arr10,order='F')

array([ 0, 27,  3, 30,  6, 33,  9, 36, 12, 39, 15, 42, 18, 45, 21, 48, 24,
       51,  1, 28,  4, 31,  7, 34, 10, 37, 13, 40, 16, 43, 19, 46, 22, 49,
       25, 52,  2, 29,  5, 32,  8, 35, 11, 38, 14, 41, 17, 44, 20, 47, 23,
       50, 26, 53])

In [51]:
temp = np.ravel(arr11)

temp[0] = 100 
print(temp)
print(arr11)

[100   1   2   3   4   5   6   7   8   9  10  11  12  13  14]
[[100   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]]


In [53]:
arr12 = np.arange(15).reshape(3,5)
temp2 = arr12.flatten()
print(arr12)
temp2

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [55]:
temp2[0]= 200
print(arr12)
temp2

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


array([200,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14])

In [58]:
temp3 = arr12.flatten(order='F')
temp3[0] = 500
print(temp3)
print(temp2)
print(arr12)

[500   5  10   1   6  11   2   7  12   3   8  13   4   9  14]
[200   1   2   3   4   5   6   7   8   9  10  11  12  13  14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [60]:
#axis 

a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [64]:
np.sum(a, axis=0)

105

In [65]:
b = a.reshape(3,5)
print(b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [66]:
np.sum(b)

105

In [67]:
np.sum(b, axis=0)

array([15, 18, 21, 24, 27])

In [68]:
np.sum(b, axis=1)

array([10, 35, 60])

In [69]:
x = np.arange(36).reshape(3,4,3)
x

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [70]:
np.sum(x, axis=0)

array([[36, 39, 42],
       [45, 48, 51],
       [54, 57, 60],
       [63, 66, 69]])

In [71]:
np.sum(x, axis=1)

array([[ 18,  22,  26],
       [ 66,  70,  74],
       [114, 118, 122]])

In [72]:
np.sum(x, axis=2)

array([[  3,  12,  21,  30],
       [ 39,  48,  57,  66],
       [ 75,  84,  93, 102]])

In [75]:
# broadcasting 

a = np.arange(12).reshape(4,3)
b = np.arange(100, 103)
c = np.arange(1000, 1004)
d = b.reshape(1,3)

print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)
d

(4, 3)
(3,)
(4,)
(1, 3)


array([[100, 101, 102]])

In [76]:
a + b

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])

In [77]:
a + c

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [78]:
a + d

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])