In [1]:
import pandas as pd 

In [3]:
data_frame = pd.read_csv('student.csv')
data_frame

이름  나이            주소
0  강경미  30  경기도 고양시 일산동구
1  고길동  20   서울시 노원구 상계동
2  개나리  19   서울시 강남구 역삼동

In [4]:
type(data_frame)

pandas.core.frame.DataFrame

In [5]:
type(data_frame.이름)

pandas.core.series.Series

In [6]:
data_frame.이름

0    강경미
1    고길동
2    개나리
Name: 이름, dtype: object

In [120]:
pd.show_versions()


INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.6.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None

pandas           : 1.0.1
numpy            : 1.18.1
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 20.0.2
setuptools       : 45.2.0.post20200210
Cython           : 0.29.15
pytest           : 5.3.5
hypothesis       : 5.5.4
sphinx           : 2.4.0
blosc            : None
feather          : None
xlsxwriter       : 1.2.7
lxml.etree       : 4.5.0
html5lib         : 1.0.1
pymysql          : None
psycopg2         : None
jinja2           : 2.11.1
IPython          : 7.12.0
pandas_datareader: None
bs4              : 4.8.2
bottleneck       : 1.3.2
fastparquet      : None
gcsfs            : None
lxml.etree       : 4

In [10]:
data_frame.head()  #기본 - 5개

이름  나이            주소
0  강경미  30  경기도 고양시 일산동구
1  고길동  20   서울시 노원구 상계동
2  개나리  19   서울시 강남구 역삼동

In [11]:
data_frame.tail()

이름  나이            주소
0  강경미  30  경기도 고양시 일산동구
1  고길동  20   서울시 노원구 상계동
2  개나리  19   서울시 강남구 역삼동

In [12]:
data_frame.head(n=2)

이름  나이            주소
0  강경미  30  경기도 고양시 일산동구
1  고길동  20   서울시 노원구 상계동

In [13]:
data_frame.tail(1)

이름  나이           주소
2  개나리  19  서울시 강남구 역삼동

In [14]:
df = pd.read_csv('student.txt')

In [15]:
df

이름  나이            주소
0  강경미  30  경기도 고양시 일산동구
1  고길동  20   서울시 노원구 상계동
2  개나리  19   서울시 강남구 역삼동

In [16]:
df = pd.read_csv('student_tab.txt')
df

이름\t나이\t주소
0  강경미\t30\t경기도 고양시 일산동구
1   고길동\t20\t서울시 노원구 상계동
2   개나리\t19\t서울시 강남구 역삼동

In [18]:
df = pd.read_csv('student_tab.txt', delimiter='\t')
df

이름  나이            주소
0  강경미  30  경기도 고양시 일산동구
1  고길동  20   서울시 노원구 상계동
2  개나리  19   서울시 강남구 역삼동

In [19]:
df = pd.read_csv('student_data.txt')
df

강경미  30 경기도 고양시 일산동구
0  고길동  20  서울시 노원구 상계동
1  개나리  19  서울시 강남구 역삼동

In [20]:
df = pd.read_csv('student_data.txt', header=None)
df

0   1             2
0  강경미  30  경기도 고양시 일산동구
1  고길동  20   서울시 노원구 상계동
2  개나리  19   서울시 강남구 역삼동

In [21]:
df.columns=['이름','나이','주소']
df

이름  나이            주소
0  강경미  30  경기도 고양시 일산동구
1  고길동  20   서울시 노원구 상계동
2  개나리  19   서울시 강남구 역삼동

In [22]:
df = pd.read_csv('student_data.txt', header=None, names=['이름','나이','주소'])
df

이름  나이            주소
0  강경미  30  경기도 고양시 일산동구
1  고길동  20   서울시 노원구 상계동
2  개나리  19   서울시 강남구 역삼동

### Series - pandas 가 제공하는 객체. 
- numpy 의 ndarray를 기반으로 인덱싱을 추가한 1차원 배열!! 
- 인덱스를 지정하지 않으면, 기본적으로는 ndarray와 같이 0부터
시작하는 인덱스를 생성, 지정할 경우 명시적으로 지정된 index를 사용
- 같은 타입의 0개 이상의 데이터를 가질 수 있다. 

In [23]:
#series  생성해보기. 

pd.Series([1,2,3])

0    1
1    2
2    3
dtype: int64

In [24]:
pd.Series(['a','b','c'])

0    a
1    b
2    c
dtype: object

In [30]:
import numpy as np
s = pd.Series(np.arange(100)).head()

In [31]:
s

0    0
1    1
2    2
3    3
4    4
dtype: int32

In [32]:
pd.Series([1,2,3],[100,200,300])

100    1
200    2
300    3
dtype: int64

In [33]:
pd.Series([1,2,3],['a','b','c'])

a    1
b    2
c    3
dtype: int64

In [36]:
s2 = pd.Series([1,2,3],['a','b','c'],dtype=np.int16)
s2

a    1
b    2
c    3
dtype: int16

In [37]:
s2.index

Index(['a', 'b', 'c'], dtype='object')

In [38]:
s2.values

array([1, 2, 3], dtype=int16)

In [42]:
s_name= data_frame.이름
s_name

0    강경미
1    고길동
2    개나리
Name: 이름, dtype: object

In [43]:
s_name[0]


'강경미'

In [45]:
s_name[3] = '박지영'
s_name[3]

'박지영'

In [46]:
s_name

0    강경미
1    고길동
2    개나리
3    박지영
Name: 이름, dtype: object

In [47]:
s_name[2]='손채연'
s_name

0    강경미
1    고길동
2    손채연
3    박지영
Name: 이름, dtype: object

In [48]:
s = pd.Series([1,2,1,1,24,4,3,2,4,4,5,np.NaN])
s

0      1.0
1      2.0
2      1.0
3      1.0
4     24.0
5      4.0
6      3.0
7      2.0
8      4.0
9      4.0
10     5.0
11     NaN
dtype: float64

In [49]:
len(s)

12

In [50]:
s.size

12

In [51]:
s.shape

(12,)

In [52]:
s.unique()

array([ 1.,  2., 24.,  4.,  3.,  5., nan])

In [53]:
s.count()

11

In [58]:
arr = np.array([3,3,3,np.NaN])
arr

array([ 3.,  3.,  3., nan])

In [59]:
arr.mean()

nan

In [60]:
s2 = pd.Series(arr)
s2

0    3.0
1    3.0
2    3.0
3    NaN
dtype: float64

In [61]:
s2.mean()

3.0

In [62]:
s.value_counts()

4.0     3
1.0     3
2.0     2
5.0     1
3.0     1
24.0    1
dtype: int64

In [63]:
s

0      1.0
1      2.0
2      1.0
3      1.0
4     24.0
5      4.0
6      3.0
7      2.0
8      4.0
9      4.0
10     5.0
11     NaN
dtype: float64

In [64]:
s[2]

1.0

In [68]:
s[[2,7]].value_counts()

2.0    1
1.0    1
dtype: int64

In [69]:
#연산 

s1 = pd.Series([1,2,3,4],['a','b','c','d'])

In [71]:
s2 = pd.Series([6,2,5,3],['d','c','b','a'])

In [72]:
s1

a    1
b    2
c    3
d    4
dtype: int64

In [73]:
s2

d    6
c    2
b    5
a    3
dtype: int64

In [74]:
#인덱스 기준 연산
s1 + s2

a     4
b     7
c     5
d    10
dtype: int64

In [76]:
print(s1)
#산술연산 
s1 ** 2

a    1
b    2
c    3
d    4
dtype: int64


a     1
b     4
c     9
d    16
dtype: int64

In [77]:
s1 ** s2

a       1
b      32
c       9
d    4096
dtype: int64

In [78]:
#index 짝이 안맞으면???   -  결과는 NaN 
s1['e'] = 9
s2['k'] = 20

In [79]:
s1

a    1
b    2
c    3
d    4
e    9
dtype: int64

In [80]:
s2

d     6
c     2
b     5
a     3
k    20
dtype: int64

In [81]:
s1 + s2

a     4.0
b     7.0
c     5.0
d    10.0
e     NaN
k     NaN
dtype: float64

In [82]:
s3 = pd.Series(np.arange(10),np.arange(10)+1)

In [83]:
s3

1     0
2     1
3     2
4     3
5     4
6     5
7     6
8     7
9     8
10    9
dtype: int32

In [84]:
#Boolean 연산

s3 > 5

1     False
2     False
3     False
4     False
5     False
6     False
7      True
8      True
9      True
10     True
dtype: bool

In [87]:
s4 = s3[s3 > 5]

In [86]:
s3

1     0
2     1
3     2
4     3
5     4
6     5
7     6
8     7
9     8
10    9
dtype: int32

In [88]:
s4

7     6
8     7
9     8
10    9
dtype: int32

In [89]:
s5 = s3[s3 % 2 == 0]
s5

1    0
3    2
5    4
7    6
9    8
dtype: int32

In [90]:
s3.index > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [91]:
s6 = s3[s3.index > 5]
s6

6     5
7     6
8     7
9     8
10    9
dtype: int32

In [93]:
s6 = s3[(s3>3) & (s3<8)]
s6

5    4
6    5
7    6
8    7
dtype: int32

In [97]:
(s3>7).sum()

2

In [99]:
(s3[s3>7]).sum()

17

In [100]:
s = pd.Series(np.arange(100,105),['a','b','c','d','e'])
s

a    100
b    101
c    102
d    103
e    104
dtype: int32

In [101]:
s['a'] = 200

In [102]:
s

a    200
b    101
c    102
d    103
e    104
dtype: int32

In [103]:
s['f'] = 105
s

a    200
b    101
c    102
d    103
e    104
f    105
dtype: int64

In [110]:
ss = s.drop('a')

In [111]:
ss

b    101
c    102
d    103
e    104
dtype: int64

In [107]:
s.drop('f',inplace=True)
s

a    200
b    101
c    102
d    103
e    104
dtype: int64

In [112]:
s

a    200
b    101
c    102
d    103
e    104
dtype: int64

In [116]:
#인덱스여러개에 접근
s[['a','b']] = [10,20]

In [117]:
s

a     10
b     20
c    102
d    103
e    104
dtype: int64

In [118]:
s[1:3]

b     20
c    102
dtype: int64

In [119]:
s['a':'c']

a     10
b     20
c    102
dtype: int64