In [1]:
import numpy as np

In [4]:
#시퀀스 데이터를 이용한 ndarray (배열) 생성
data1=[1,2,3,4,5,6]
arr1 = np.array(data1)
print(type(arr1))
arr1

<class 'numpy.ndarray'>


array([1, 2, 3, 4, 5, 6])

In [5]:
data2 = [[1,2,3],[4,5,6]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
data3 = [1.2,2.3,3.3]
arr3 = np.array(data3)
arr3

array([1.2, 2.3, 3.3])

In [7]:
arr1.dtype

dtype('int32')

In [8]:
arr3.dtype

dtype('float64')

In [10]:
data4=[1,2,3.0,4,5]
arr4 = np.array(data4)
arr4

array([1., 2., 3., 4., 5.])

In [11]:
arr4.dtype

dtype('float64')

In [12]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [15]:
np.arange(1,10,2,dtype='float')

array([1., 3., 5., 7., 9.])

In [36]:
arr5 = np.arange(6).reshape(2,3)
print(arr5)
arr5.shape

[[0 1 2]
 [3 4 5]]


(2, 3)

In [18]:
arr1.shape

(6,)

In [20]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
np.ones((3,4,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [23]:
np.empty((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
np.full((3,4),3)

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

In [26]:
np.zeros((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [28]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [29]:
np.linspace(1,10,3)

array([ 1. ,  5.5, 10. ])

In [30]:
np.linspace(1,10,4)

array([ 1.,  4.,  7., 10.])

In [31]:
data6 = ['1','2','3']
arr6 = np.array(data6)
arr6

array(['1', '2', '3'], dtype='<U1')

In [32]:
arr6.dtype

dtype('<U1')

In [33]:
arr6_num = arr6.astype(int)
arr6_num.dtype

dtype('int32')

In [34]:
arr6_num

array([1, 2, 3])

In [37]:
#random 
#rand() - 0~1 사이의 값으로 ndarray생성  (0포함, 1은 불포함)

np.random.rand(4,5,3)

array([[[0.35955551, 0.53125077, 0.86510534],
        [0.11256495, 0.35999723, 0.78030856],
        [0.67859172, 0.53074692, 0.28891813],
        [0.031125  , 0.07720077, 0.28875988],
        [0.14751554, 0.82502678, 0.90360013]],

       [[0.19917724, 0.75625883, 0.9758699 ],
        [0.17203296, 0.54876563, 0.1242885 ],
        [0.70542144, 0.61904788, 0.08846634],
        [0.23442743, 0.99636493, 0.70511787],
        [0.45841674, 0.21346338, 0.52145808]],

       [[0.46244833, 0.50653272, 0.88084552],
        [0.08292461, 0.66974782, 0.64280253],
        [0.12407849, 0.99517471, 0.62222646],
        [0.88948023, 0.29695916, 0.85718623],
        [0.06202998, 0.2600122 , 0.30355239]],

       [[0.69612599, 0.7934992 , 0.37764979],
        [0.8821242 , 0.43421406, 0.31226051],
        [0.91333722, 0.80476522, 0.71949411],
        [0.40422473, 0.1889756 , 0.56639882],
        [0.35644167, 0.05721067, 0.34935815]]])

In [38]:
np.random.rand(4,5)

array([[0.53368363, 0.15865465, 0.22308682, 0.38612995, 0.95770758],
       [0.5843547 , 0.75359349, 0.5012701 , 0.77283691, 0.39849928],
       [0.62417287, 0.68260969, 0.01958838, 0.32478849, 0.69415263],
       [0.20203021, 0.0184753 , 0.04019422, 0.277616  , 0.63308133]])

In [45]:
np.random.rand(4)

array([0.70038338, 0.35330054, 0.21401977, 0.83499277])

In [42]:
np.random.rand()

0.18242496391098495

In [46]:
#randn 함수 
np.random.randn(4,5,3)

array([[[-1.42787802,  1.05906008, -1.40246283],
        [ 0.95602802,  1.26946079,  1.0120021 ],
        [-0.48850187,  0.2306086 ,  0.62175536],
        [ 1.13394862,  1.02085889,  0.87105367],
        [ 1.75116523, -0.318566  ,  0.38167557]],

       [[-0.87673215, -0.5309819 ,  0.94722328],
        [ 0.81731739,  0.07648405, -0.82139431],
        [ 0.63680036, -1.39175757, -0.33568486],
        [-0.35930321,  1.85920112,  0.10126928],
        [-0.47057764, -0.62567837,  0.6820834 ]],

       [[ 1.06228313, -0.1512084 , -0.46281845],
        [-0.33736506,  0.80069636, -0.47931989],
        [ 0.60765429, -0.87861675,  0.2780889 ],
        [-0.05364749, -1.27577379,  1.24142021],
        [-1.307916  ,  1.90794021,  0.35284174]],

       [[-0.97155355,  0.06003363, -1.77548469],
        [-1.03265307, -1.62217859,  0.30348216],
        [-0.26956556,  1.94601159,  0.20392681],
        [-1.85452001,  0.40013921,  1.32223101],
        [-0.71519067,  1.54801151,  1.49104652]]])

In [49]:
np.random.randn(4)

array([ 0.45662008,  0.38859983,  0.01386812, -1.61482414])

In [85]:
# randint  특정 정수 사이에서 랜덤한 값으로 ndarray생성
np.random.seed(33)
np.random.randint(1,100,size=(5))

array([21,  8, 89, 67, 19])

In [51]:
np.random.randint(1,100,size=(3,5))

array([[92, 54, 20, 58, 37],
       [33, 40, 39, 45, 66],
       [98, 37, 37, 75, 70]])

In [52]:
np.random.randint(10)

5

In [53]:
np.random.randint(1,10)

5

In [54]:
np.random.randint(1,10,size=(3))

array([8, 7, 9])

In [62]:
# seed - 랜덤한 값을 동일하게 다시 생성하고 할때..  
np.random.seed(32)
np.random.randn(3,4)

array([[-0.34889445,  0.98370343,  0.58092283,  0.07028444],
       [ 0.77753268,  0.58195875,  1.47179053,  1.66318101],
       [-0.26117712, -0.68867681, -0.69492326,  1.94042346]])

In [63]:
# choice - 주어진 1차원 ndarray로 부터 랜덤으로 샘플링함. 
sample_data = np.array([10,20,30,40,50])
np.random.choice(sample_data, size=(2,3))

array([[30, 50, 50],
       [20, 20, 40]])

In [67]:
# choice - 정수가 주어지면 np.arange(정수) 으로 간주함. 
np.random.choice(100, size=(4,5),replace=False)

array([[52,  4, 13, 59, 46],
       [49, 63,  0, 83, 93],
       [95, 19, 34, 33, 50],
       [31, 10, 89, 38,  1]])

In [68]:
np.random.uniform(1.0,3.0, size=(4,5))

array([[2.03577605, 1.27095896, 1.97426542, 2.18433578, 2.02382161],
       [1.5188114 , 2.94239132, 1.01642367, 1.98331991, 1.53767328],
       [2.92039906, 2.26819702, 2.29662774, 2.69078152, 1.02954082],
       [1.07390946, 1.60867219, 2.89354272, 2.47652281, 1.52170131]])

In [69]:
np.random.normal(size=(3,4))

array([[-0.25534864, -0.9504092 ,  1.75754042, -0.13302541],
       [-1.23304062,  0.91672842, -0.13922791, -0.45817201],
       [ 1.64085405,  1.18602198,  0.45170823,  0.64290859]])

In [70]:
np.random.randn(3,4)

array([[-0.45521717, -0.4587479 ,  1.38477594,  1.03745311],
       [ 1.45179778,  0.07250464,  1.33610706,  0.50971165],
       [ 1.33632253, -0.49582272,  0.38459956, -1.06537199]])

In [71]:
# 배열의 연산 

arr1 = np.array([10, 20, 30, 40]) 
arr2 = np.array([1, 2, 3, 4]) 

arr1 + arr2 


array([11, 22, 33, 44])

In [72]:
arr3 = np.arange(15).reshape(3,5)
arr3

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [79]:
arr4 = np.random.rand(15).reshape(3,5)
arr4

array([[0.27031883, 0.88664242, 0.93720068, 0.98042759, 0.95661289],
       [0.93104374, 0.28506843, 0.88163332, 0.88226434, 0.92946005],
       [0.67940704, 0.80551398, 0.01291082, 0.50129269, 0.87410296]])

In [80]:
arr3 + arr4

array([[ 0.27031883,  1.88664242,  2.93720068,  3.98042759,  4.95661289],
       [ 5.93104374,  6.28506843,  7.88163332,  8.88226434,  9.92946005],
       [10.67940704, 11.80551398, 12.01291082, 13.50129269, 14.87410296]])

In [81]:
np.add(arr3,arr4)

array([[ 0.27031883,  1.88664242,  2.93720068,  3.98042759,  4.95661289],
       [ 5.93104374,  6.28506843,  7.88163332,  8.88226434,  9.92946005],
       [10.67940704, 11.80551398, 12.01291082, 13.50129269, 14.87410296]])

In [82]:
np.divide(arr1,arr2)

array([10., 10., 10., 10.])

In [86]:
np.random.seed(33)
np.random.randint(1,100,size=(5))

array([21,  8, 89, 67, 19])

In [88]:
print(arr1)
arr1 + 2

[10 20 30 40]


array([12, 22, 32, 42])

In [89]:
arr1 > 20 

array([False, False,  True,  True])

In [91]:
#통계함수 - 평균, 분산, 최대, 최소...... 
print(arr1)

np.mean(arr1)

[10 20 30 40]


25.0

In [92]:
arr1.mean()

25.0

In [93]:
np.max(arr1)

40

In [94]:
np.min(arr1)

10

In [96]:
print(np.median(arr1), np.std(arr1))

25.0 11.180339887498949


In [98]:
#집계 함수 
np.sum(arr1)

100

In [100]:
print(arr1)
np.cumsum(arr1)

[10 20 30 40]


array([ 10,  30,  60, 100], dtype=int32)

In [102]:
#any, all 함수 
# any - 특정 조건을 만족하는 것이 하나라도 존재하면 True, 아니면 False
# all - 모든 원소가 특정 조건에 만족해야만 True, 아니면 False

arr5 = np.random.randn(10)
print(arr5)

[ 0.63443794  1.40935364 -0.96912075 -0.09047386  1.06918594 -0.44105642
 -0.68655947  0.64323539 -0.49818344 -1.55574022]


In [103]:
arr5 > 0


array([ True,  True, False, False,  True, False, False,  True, False,
       False])

In [104]:
np.any(arr5 > 0)

True

In [106]:
np.all(arr5 > 0)

False

In [107]:
# where 함수 
# 조건에 따라서 선별적으로 값을 선택 

np.where(arr5 > 0 , arr5, 0)

array([0.63443794, 1.40935364, 0.        , 0.        , 1.06918594,
       0.        , 0.        , 0.64323539, 0.        , 0.        ])